"""Constants for LED effects and animations."""

# Colors (RGB tuples)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_YELLOW = (255, 255, 100)
COLOR_DARK_BLUE = (0, 0, 139)
COLOR_LIGHT_GREY = (255, 255, 255)

# Night colors for starfield effect
COLOR_DARK_BLUE_1 = (0, 0, 80)
COLOR_DARK_BLUE_2 = (0, 0, 120)
COLOR_DARK_BLUE_3 = (0, 0, 180)
COLOR_DARK_BLUE_4 = (0, 0, 255)
COLOR_PURPLE = (50, 0, 50)

# Fade settings
FADE_OUT_STEPS = 50
FADE_OUT_DELAY = 0.02

# Lighting effect settings
LIGHTING_FADE_SPEED = 0.5
LIGHTING_MIN_BURN_TIME = 10
LIGHTING_MAX_BURN_TIME = 30

# Fireworks fade rates
FIREWORKS_FADE_R = 15
FIREWORKS_FADE_G = 20
FIREWORKS_FADE_B = 20

# Timing (seconds)
MAIN_LOOP_INTERVAL = 30
SUNRISE_SUNSET_DURATION = 30  # minutes before/after actual sunrise/sunset

# Effect parameters
RAIN_BLUE_MIN = 50
RAIN_BLUE_MAX = 255
RAIN_OTHER_MIN = 0
RAIN_OTHER_MAX = 5

# Thunder flash settings
THUNDER_CHANCE = 250  # 1 in 250 chance per frame
THUNDER_MIN_FLASHES = 3
THUNDER_MAX_FLASHES = 7
THUNDER_MIN_FLASH_DURATION = 0.05
THUNDER_MAX_FLASH_DURATION = 0.2
THUNDER_MIN_PAUSE = 0.1
THUNDER_MAX_PAUSE = 0.5

# Snow settings
SNOW_FALL_DELAY = 0.2

# Effect update delays
RAIN_UPDATE_DELAY = 0.1
FIREWORKS_UPDATE_DELAY = 0.05
LIGHTING_UPDATE_DELAY = 0.05

# Weather intensity presets
INTENSITY_DRIZZLE = 15
INTENSITY_RAIN = 35
INTENSITY_THUNDER = 40
INTENSITY_SNOW = 15
INTENSITY_FIREWORKS = 50
INTENSITY_DAY = 60

# Brightness presets
BRIGHTNESS_NIGHT = 1.0
BRIGHTNESS_SNOW = 1.0
BRIGHTNESS_SNOW_NIGHT = 1.0
BRIGHTNESS_SUNRISE_SUNSET = 1.0

# Christmas settings
CHRISTMAS_INTENSITY = 100
CHRISTMAS_MAX_LEDS = 15
CHRISTMAS_RED_WEIGHT = 60
CHRISTMAS_GREEN_WEIGHT = 40

# Night (stars) settings
NIGHT_INTENSITY = 100
NIGHT_MAX_LEDS = 20
NIGHT_COLOR_WEIGHTS = [15, 15, 15, 20, 30, 5]  # for COLOR_DARK_BLUE_1-4, COLOR_PURPLE, COLOR_WHITE

# Day settings
DAY_MIN_LEDS = 40
DAY_MAX_LEDS = 80

# Special dates
CHRISTMAS_MONTH = 12
CHRISTMAS_EVE_DAY = 24
CHRISTMAS_EVE_HOUR = 18
CHRISTMAS_DAY = 25
BOXING_DAY = 26
NEW_YEAR_MONTH = 1
NEW_YEAR_MAX_DAY = 6
